# Garante a porta 8081
quarkus.http.port=8081

# Desliga QUALQUER tentativa de usar Docker automaticamente
quarkus.devservices.enabled=false
quarkus.langchain4j.devservices.open-webui.enabled=false

# Banco de Dados
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5436/confirmaai}
%dev.quarkus.hibernate-orm.database.generation=drop-and-create

# Configuração da IA
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.temperature=0.0

# Força o motor do Quartz a ligar para usarmos agendamento dinâmico
quarkus.scheduler.start-mode=forced

# Evolution API
evolution-api/mp-rest/url=${EVOLUTION_API_URL}
evolution-api.token=${EVOLUTION_API_GLOBAL_TOKEN}

# A propriedade global webhook.security.token foi REMOVIDA.
# A segurança agora é individual (por tenant/clínica).

# Fuso horário padronizado da aplicação e banco de dados
quarkus.hibernate-orm.jdbc.timezone=America/Fortaleza
quarkus.jackson.timezone=America/Fortaleza
user.timezone=America/Fortaleza

# Configuração do Quartz para usar o PostgreSQL
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true