# Garante a porta 8081
quarkus.http.port=8081

# Desliga QUALQUER tentativa de usar Docker automaticamente
quarkus.devservices.enabled=false
quarkus.langchain4j.devservices.open-webui.enabled=false

# Banco de Dados
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/confirmaai
%dev.quarkus.hibernate-orm.database.generation=drop-and-create

# Configura??o da IA
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.temperature=0.0

# For?a o motor do Quartz a ligar para usarmos agendamento din?mico
quarkus.scheduler.start-mode=forced

# Evolution API
evolution-api/mp-rest/url=https://sua-url-da-api.com
evolution-api.token=seu-token-aqui

# Medida de seguranca para o Webhook (Gere um UUID ou string complexa para producao)
webhook.security.token=meu-token-secreto-confirmaai-123
